server:
  bindPort : 27202
database:
  host : localhost
  port : 5432
  username : postgres
  password : server@1S
  databaseName : postgres
  sslMode : disable
redis:
  host: localhost
  databaseName: redis
metrics:
  host: localhost
  port: 30002